# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: e2e github actions

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Test
      run: |
        npm install
        npx codeceptjs run --grep "\@accounts|\@analytics|\@email|\@explore_analytics|\@settings|\@team" --plugins allure
      env:
        CI: true
        TESTING_ENV: 'STAGING'
        STAGING_URL: ${{ secrets.STAGING_URL }}
        STAGING_USERNAME: ${{ secrets.STAGING_USERNAME }}
        STAGING_PASSWORD: ${{ secrets.STAGING_PASSWORD }}
        STAGING_ENDPOINT: ${{ secrets.STAGING_ENDPOINT }}
        STAGING_BEARER: ${{ secrets.STAGING_BEARER }}
      
    - name: Send Results and Generate Allure Report
      uses: Xotabu4/send-to-allure-server-action@1
      id: allure-report
      # always() needed because we want report for failed tests as well
      if: ${{ always() }}
      with:
        allure-server-url: 'http://51.79.156.44:8080/'
        allure-results: './output'
